# Generated by Django 6.0.4 on 2026-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='appointment_day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
