# Generated by Django 6.0.4 on 2026-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_messages', '0003_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
